<?php
$title = 'Add new course';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$strCourseDescription = $form->get('strCourseDescription');
$strCourseDescription->setAttribute('class', 'form-control');
$strCourseDescription->setAttribute('placeholder', 'Description course');

// This provides a default CSS class and placeholder text for the artist element:
$curCourseCost = $form->get('curCourseCost');
$curCourseCost->setAttribute('class', 'form-control');
$curCourseCost->setAttribute('placeholder', 'Cost course');

// This provides a default CSS class and placeholder text for the artist element:
    $intCourseDurationYears = $form->get('intCourseDurationYears');
    $intCourseDurationYears->setAttribute('class', 'form-control');
    $intCourseDurationYears->setAttribute('placeholder', 'Duration years');

// This provides a default CSS class and placeholder text for the artist element:
    $memNotes = $form->get('memNotes');
    $memNotes->setAttribute('class', 'form-control');
    $memNotes->setAttribute('placeholder', 'Notes');    

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('courselist', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($strCourseDescription) ?>
    <?= $this->formElement($strCourseDescription) ?>
    <?= $this->formElementErrors()->render($strCourseDescription, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($curCourseCost) ?>
    <?= $this->formElement($curCourseCost) ?>
    <?= $this->formElementErrors()->render($curCourseCost, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($intCourseDurationYears) ?>
    <?= $this->formElement($intCourseDurationYears) ?>
    <?= $this->formElementErrors()->render($intCourseDurationYears, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($memNotes) ?>
    <?= $this->formElement($memNotes) ?>
    <?= $this->formElementErrors()->render($memNotes, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();