<?php
$title = 'My position';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('jposition', ['action' => 'add']) ?>">Add new position</a>
</p>

<table class="table">
<tr>
    <th>Position</th>
    
    <th>&nbsp;</th>
</tr>
<?php foreach ($jpositions as $jposition) : ?>
    <tr>
        <td><?= $this->escapeHtml($jposition->strEmpPosition) ?></td>
        
        </td>
        <td>
            <a href="<?= $this->url('jposition', ['action' => 'edit', 'id' => $jposition->id]) ?>">Edit</a>
            <a href="<?= $this->url('jposition', ['action' => 'delete', 'id' => $jposition->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>