<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit contact';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$strContactType = $form->get('strContactType');
$strContactType->setAttribute('class', 'form-control');
$strContactType->setAttribute('placeholder', 'type contact');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('contact', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($strContactType) ?>
    <?= $this->formElement($strContactType) ?>
    <?= $this->formElementErrors()->render($strContactType, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();